{
 "title": "Adidas Running (Rutastic) Dashboard",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Overall Sessions per Sport ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT sport_type.activity, COUNT(*) as sessions_count\r\nFROM sessions\r\nJOIN sport_type ON sessions.sport_type_id::int = sport_type.id\r\nGROUP BY sport_type.activity\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Fastest 10km",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT fs.distance,  fs.started_at, fs.duration\r\nFROM fastest_segments fs\r\nJOIN sessions s ON fs.sessions_id = s.id\r\nJOIN sport_type st ON s.sport_type_id::int = st.id\r\nWHERE st.activity = 'Running'\r\nAND fs.distance = '10km'\r\nORDER BY fs.duration ASC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Fastest 5km",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT fs.distance,  fs.started_at, fs.duration\r\nFROM fastest_segments fs\r\nJOIN sessions s ON fs.sessions_id = s.id\r\nJOIN sport_type st ON s.sport_type_id::int = st.id\r\nWHERE st.activity = 'Running'\r\nAND fs.distance = '5km'\r\nORDER BY fs.duration ASC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Fastest 1km",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT fs.distance,  fs.started_at, fs.duration\r\nFROM fastest_segments fs\r\nJOIN sessions s ON fs.sessions_id = s.id\r\nJOIN sport_type st ON s.sport_type_id::int = st.id\r\nWHERE st.activity = 'Running'\r\nAND fs.distance = '1km'\r\nORDER BY fs.duration ASC\r\nLIMIT 1"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT fs.started_at\r\nFROM fastest_segments fs\r\nJOIN sessions s ON fs.sessions_id = s.id\r\nJOIN sport_type st ON s.sport_type_id::int = st.id\r\nWHERE st.activity = 'Running'\r\nAND fs.distance = '10km'\r\nORDER BY fs.duration ASC\r\nLIMIT 1"
    }
   ]
  },
  {
   "type": "table",
   "description": "Date where the fastest 5 km were performed",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT fs.started_at\r\nFROM fastest_segments fs\r\nJOIN sessions s ON fs.sessions_id = s.id\r\nJOIN sport_type st ON s.sport_type_id::int = st.id\r\nWHERE st.activity = 'Running'\r\nAND fs.distance = '5km'\r\nORDER BY fs.duration ASC\r\nLIMIT 1"
    }
   ]
  },
  {
   "type": "table",
   "description": "Date where the fastest 1 km were performed",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT fs.started_at\r\nFROM fastest_segments fs\r\nJOIN sessions s ON fs.sessions_id = s.id\r\nJOIN sport_type st ON s.sport_type_id::int = st.id\r\nWHERE st.activity = 'Running'\r\nAND fs.distance = '1km'\r\nORDER BY fs.duration ASC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT concat(month,' ', year), SUM(distance) AS total_distance\r\nFROM sessions\r\nGROUP BY year, month\r\nORDER BY \r\nyear,\r\n  CASE \r\n    WHEN month = 'January' THEN 1 \r\n    WHEN month = 'February' THEN 2 \r\n    WHEN month = 'March' THEN 3 \r\n    WHEN month = 'April' THEN 4 \r\n    WHEN month = 'May' THEN 5 \r\n    WHEN month = 'June' THEN 6 \r\n    WHEN month = 'July' THEN 7 \r\n    WHEN month = 'August' THEN 8 \r\n    WHEN month = 'September' THEN 9 \r\n    WHEN month = 'October' THEN 10 \r\n    WHEN month = 'November' THEN 11 \r\n    WHEN month = 'December' THEN 12 \r\n  END;\r\n"
    }
   ]
  },
  {
   "title": "[Selected Time] Session Distance and Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT start_time, duration\r\nFROM sessions \r\nWHERE $__timeFilter(start_time)\t"
    },
    {
     "rawSql": "SELECT start_time, distance\r\nFROM sessions \r\nWHERE $__timeFilter(start_time)\t"
    }
   ]
  }
 ]
}